/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package werewolvesinwonderland.client.view;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JLayer;
import javax.swing.JPanel;

/**
 *
 * @author Tifani
 */
public class NewGameDialog extends JFrame {

    /**
     * Creates new form NewGameFrame
     */
    public NewGameDialog() {
        super();
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setTitle("Werewolf in Wonderland: New Game");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsername = new javax.swing.JLabel();
        lbServerAddr = new javax.swing.JLabel();
        lbServerPort = new javax.swing.JLabel();
        lbClientPort = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfServerPort = new javax.swing.JTextField();
        tfServerAddr = new javax.swing.JTextField();
        tfClientPort = new javax.swing.JTextField();
        btnStartGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbUsername.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        lbUsername.setText("Username");

        lbServerAddr.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        lbServerAddr.setText("Server Address");

        lbServerPort.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        lbServerPort.setText("Server Port");

        lbClientPort.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        lbClientPort.setText("Client Port");

        tfUsername.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N

        tfServerPort.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N

        tfServerAddr.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N

        tfClientPort.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N

        btnStartGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/werewolvesinwonderland/client/assets/button_start_game.png"))); // NOI18N
        btnStartGame.setToolTipText("");
        btnStartGame.setBorderPainted(false);
        btnStartGame.setContentAreaFilled(false);
        btnStartGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartGameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbServerPort)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbUsername)
                            .addComponent(lbServerAddr)
                            .addComponent(lbClientPort))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfClientPort, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfServerAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStartGame)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsername)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbServerAddr)
                    .addComponent(tfServerAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbServerPort)
                    .addComponent(tfServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbClientPort)
                    .addComponent(tfClientPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnStartGame)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartGameMouseClicked
        String username = tfUsername.getText();
        String serverAddress = tfServerAddr.getText();
        int serverPort = Integer.parseInt(tfServerPort.getText());
        int clientPort = Integer.parseInt(tfClientPort.getText());
        System.out.println(NewGameDialog.class.getSimpleName() +
            ": [Join Game] " +
            "Username: " + username + ", " +
            "Server Address: " + serverAddress + ", " +
            "Server Port: " + serverPort + ", " +
            "Client Port: " + clientPort);

        LoadingUI layerUI = new LoadingUI();
        JPanel panel = new JPanel() {

            @Override
            public Dimension getPreferredSize() {
                return new Dimension(400, 300);
            }
        };
        JLayer<JPanel> jlayer = new JLayer<>(panel, layerUI);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.add(jlayer);
        this.pack();
        this.setVisible(true);
        layerUI.start();
    }//GEN-LAST:event_btnStartGameMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartGame;
    private javax.swing.JLabel lbClientPort;
    private javax.swing.JLabel lbServerAddr;
    private javax.swing.JLabel lbServerPort;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JTextField tfClientPort;
    private javax.swing.JTextField tfServerAddr;
    private javax.swing.JTextField tfServerPort;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
