/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package werewolvesinwonderland.client.view;

import com.sun.deploy.uitoolkit.impl.fx.ui.FXUIFactory;
import java.awt.BorderLayout;
import java.awt.Dialog;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayer;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;

/**
 *
 * @author Tifani
 */
public class NewGameDialog extends JFrame {
    
    public interface NewGameDialogListener {
        void onJoinGameButtonClicked(String username, String serverAddress, int serverPort, int clientPort);
    }

    /**
     * Creates new form NewGameFrame
     */
    public NewGameDialog(GameFrame gameFrame) {
        super();
        try {
            dialogListener = (NewGameDialogListener) gameFrame;
        } catch (Exception e) {
            System.out.println("Game Frame must implements New Game Dialog Listener");
            e.printStackTrace();
        }
        initComponents();
        ImageIcon img = new ImageIcon(getClass().getResource("/werewolvesinwonderland/client/assets/icon_werewolf.png"));
        this.setIconImage(img.getImage());
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setTitle("Werewolf in Wonderland: New Game");
        this.setSize(new Dimension(585, 440));
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsername = new javax.swing.JLabel();
        lbServerAddr = new javax.swing.JLabel();
        lbServerPort = new javax.swing.JLabel();
        lbClientPort = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfServerPort = new javax.swing.JTextField();
        tfServerAddr = new javax.swing.JTextField();
        tfClientPort = new javax.swing.JTextField();
        btnJoinGame = new javax.swing.JButton();
        bgStatGameDialog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbUsername.setFont(new java.awt.Font("Abel", 1, 18)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(102, 51, 0));
        lbUsername.setText("Username");
        getContentPane().add(lbUsername);
        lbUsername.setBounds(68, 100, 76, 24);

        lbServerAddr.setFont(new java.awt.Font("Abel", 1, 18)); // NOI18N
        lbServerAddr.setForeground(new java.awt.Color(102, 51, 0));
        lbServerAddr.setText("Server Address");
        getContentPane().add(lbServerAddr);
        lbServerAddr.setBounds(68, 158, 120, 24);

        lbServerPort.setFont(new java.awt.Font("Abel", 1, 18)); // NOI18N
        lbServerPort.setForeground(new java.awt.Color(102, 51, 0));
        lbServerPort.setText("Server Port");
        getContentPane().add(lbServerPort);
        lbServerPort.setBounds(68, 213, 85, 24);

        lbClientPort.setFont(new java.awt.Font("Abel", 1, 18)); // NOI18N
        lbClientPort.setForeground(new java.awt.Color(102, 51, 0));
        lbClientPort.setText("Client Port");
        getContentPane().add(lbClientPort);
        lbClientPort.setBounds(68, 270, 82, 24);

        tfUsername.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        getContentPane().add(tfUsername);
        tfUsername.setBounds(191, 97, 230, 30);

        tfServerPort.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        getContentPane().add(tfServerPort);
        tfServerPort.setBounds(191, 210, 230, 30);

        tfServerAddr.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        getContentPane().add(tfServerAddr);
        tfServerAddr.setBounds(191, 155, 230, 30);

        tfClientPort.setFont(new java.awt.Font("Abel", 0, 18)); // NOI18N
        getContentPane().add(tfClientPort);
        tfClientPort.setBounds(191, 267, 230, 30);

        btnJoinGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/werewolvesinwonderland/client/assets/btn_joingame.png"))); // NOI18N
        btnJoinGame.setToolTipText("");
        btnJoinGame.setBorderPainted(false);
        btnJoinGame.setContentAreaFilled(false);
        btnJoinGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJoinGameMouseClicked(evt);
            }
        });
        getContentPane().add(btnJoinGame);
        btnJoinGame.setBounds(180, 320, 209, 47);

        bgStatGameDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/werewolvesinwonderland/client/assets/bg_startgame_dialog.png"))); // NOI18N
        getContentPane().add(bgStatGameDialog);
        bgStatGameDialog.setBounds(0, 0, 570, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJoinGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinGameMouseClicked
        String username = tfUsername.getText();
        String serverAddress = tfServerAddr.getText();
        if (username != null && !username.equals("") &&
                serverAddress != null && !serverAddress.equals("") &&
                tfServerPort.getText() != null && !tfServerPort.getText().equals("") &&
                tfClientPort.getText() != null && !tfClientPort.getText().equals("")) {
            try {                
                int serverPort = Integer.parseInt(tfServerPort.getText());
                int clientPort = Integer.parseInt(tfClientPort.getText());
                this.setVisible(false);
                dialogListener.onJoinGameButtonClicked(username, serverAddress, serverPort, clientPort);
            } catch (Exception e) {
                showMessageDialog(null, "Please fill in all of the fields in properly!!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            showMessageDialog(null, "Please fill in all of the fields!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnJoinGameMouseClicked

    private NewGameDialogListener dialogListener;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgStatGameDialog;
    private javax.swing.JButton btnJoinGame;
    private javax.swing.JLabel lbClientPort;
    private javax.swing.JLabel lbServerAddr;
    private javax.swing.JLabel lbServerPort;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JTextField tfClientPort;
    private javax.swing.JTextField tfServerAddr;
    private javax.swing.JTextField tfServerPort;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
